### ISSUE TITLE
FP: incorrect attacker identification

### ISSUE THREAD

**Issue by christian-forta** [tf0rs/forta-address-poisoning-agent#6]
https://explorer.forta.network/alert/0xf213a1f913e5de30902020c8bda4192d7b16069e4fa82c2b5db083a4070ff359

0x5f1a7b7e5d899e0379d0e536e3de825b73676a9c isnt the attacker address. Seems like neither the sender nor recipient is the actual attacker, but rather just the contract?

**Comment by christian-forta** [comment]
Same here https://explorer.forta.network/alert/0x210dd39db1950dde4c2c1d106fc60210bc91d6224afba8dfe4883af359724a88

for address 0xc23a5a57764404e85a830756243f3cebe655174b

**Comment by tf0rs** [comment]
On the first example I think I disagree. If you look at transactions for https://etherscan.io/txs?a=0xd66b84b6eecfeb2aeeb0f33e855ae43137a3a897 beginning with 0x5d4261ae940f0c09d7a0033e9189dac5c5aa2169a96721796ce0b48490613728. I interpret that as a successful theft of 150 ETH.

**Comment by christian-forta** [comment]
you are absolutely correct, @tf0rs . Sorry for the noise. See address poisoners even confuse me....ugh

**Comment by tf0rs** [comment]
No worries. Still good to raise!
