### ISSUE TITLE
FN issue

### ISSUE THREAD

**Issue by Ivan1905** [tf0rs/forta-address-poisoning-agent#7]
Hi Trevor,

Opening an issue in order to tackle the following FN. This transaction was not picked up by the address poisoning bot https://etherscan.io/tx/0xd65b7f9b1497a5e2afaf65b36d3d6f111de8c888b6db4be94b5eace359e2d491

Wondering if something should be tweaked in order to have caught it.

**Comment by tf0rs** [comment]
Thanks Ivan, I've pushed a new version that should handle this.
