### ISSUE TITLE
FP issues - Address poisoning

### ISSUE THREAD

**Issue by Ivan1905** [tf0rs/forta-address-poisoning-agent#9]
Hi there,

For some reason there were a bunch of FPs for the week that has passed.
Attaching some examples:

1. Alert [here](https://explorer.forta.network/alert/0x7f4e035dbb9be147bec12aeff344bf6cac5115d14a5f14996c43dee195645ed1)
2. Alert [here](https://explorer.forta.network/alert/0x9684c53964e17a64eb9bbbc84b1dc6f924b3d70165f6d935d3dbd470d13459c5)
3. Alert [here](https://explorer.forta.network/alert/0xb1f64ac37f2317ecb982a01eb08dfc2420fa5ee9966f50ebc0a5cf404b047c7b) 

Seems that it is coming from the fake token which is labeling addresses that are receiving transfers from coinbase.

Thanks!

**Comment by tf0rs** [comment]
Thanks, I'd introduced a bug in the token symbol validation. Fixed now.
